name: JHC_MIS
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase: ^9.0.3
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  image_picker: ^1.1.2
  flutter_svg: ^2.0.9
  firebase_core: ^2.32.0
  firebase_storage: ^11.7.7
  provider: ^6.1.2
  google_nav_bar: ^5.0.6
  curved_navigation_bar: ^1.0.5
  uuid: ^4.4.0
  intl: ^0.19.0
  fluttertoast: ^8.2.8
  path_provider: ^2.1.4
  excel: ^4.0.6
  permission_handler: ^11.3.1
  firebase_messaging: ^14.9.4
  device_info_plus: ^10.1.2
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets\fonts\Ubuntu-Regular.ttf
        - asset: assets\fonts\Ubuntu-Bold.ttf
          weight: 700
        - asset: assets\fonts\Ubuntu-Italic.ttf
          style: italic
        - asset: assets\fonts\Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
